name: deciplus-notifier

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install -g aws-cdk

      - run: npm i

      - run: npm run test

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - run: cdk bootstrap

      - run: cdk deploy --require-approval never
        env:
          DECIPLUS_EMAIL: ${{ secrets.DECIPLUS_EMAIL }}
          DECIPLUS_PASSWORD: ${{ secrets.DECIPLUS_PASSWORD }}
